# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
   vmImage: 'macOS 10.13'
   
steps:
- script: |
    sudo xcode-select -switch /Applications/Xcode_10.app
    fastlane prepare 
  displayName: "Setup environment"

- script: |
    fastlane build
  displayName: "Build"

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: "build"
    artifactName: "Build logs"
  condition: succeededOrFailed()
  displayName: "Store build log"

- script: |
    fastlane test
  displayName: "Test"

- task: PublishTestResults@2
  inputs:
    testResultsFiles: 'test/*.junit'
  condition: succeededOrFailed()
  displayName: "Publish test results"

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: "test"
    artifactName: "Test logs"
  condition: succeededOrFailed()
  displayName: "Store test log"